name: CI Advanced

on:
  push:
    paths:
      - 'MLProject/modelling_tuning.py'
      - 'MLProject/dataset_preprocessing/**'

jobs:
  train_advanced:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yml

      - name: Set DagsHub environment variables
        run: |
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run modelling_tuning.py
        working-directory: MLProject
        run: |
          python modelling_tuning.py
