name: CI Advanced

on:
  push:
    paths:
      - 'MLProject/modelling_tuning.py'
      - 'MLProject/dataset_preprocessing/**'

jobs:
  train_advanced:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yml
          cache: true

      - name: Install extra pip packages (optional)
        run: |
          pip install --upgrade pip
          pip install mlflow matplotlib

      - name: Set DagsHub environment variables
        run: |
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run modelling_tuning.py
        working-directory: MLProject
        run: |
          echo "[INFO] Running modelling_tuning.py for Advanced CI"
          python modelling_tuning.py

      - name: Upload MLflow local artefacts (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns
